/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#4f378a',
        'primary-container': '#6750a4',
        'on-primary': '#ffffff',
        'on-primary-container': '#e0d2ff',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#cfbcff',
        'inverse-primary': '#cfbcff',
        secondary: '#63597c',
        'secondary-container': '#e1d4fd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#645a7d',
        tertiary: '#765b00',
        'tertiary-container': '#c9a74d',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#503d00',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#fdf7ff',
        'surface-dim': '#ded8e0',
        'surface-bright': '#fdf7ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8f2fa',
        'surface-container': '#f2ecf4',
        'surface-container-high': '#ece6ee',
        'surface-container-highest': '#e6e0e9',
        'on-surface': '#1d1b20',
        'on-surface-variant': '#494551',
        'surface-variant': '#e6e0e9',
        outline: '#7a7582',
        'outline-variant': '#cbc4d2',
        background: '#fdf7ff',
        'on-background': '#1d1b20',
        'inverse-surface': '#322f35',
        'inverse-on-surface': '#f5eff7',
        'surface-tint': '#6750a4',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
      },
      spacing: {
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
      },
      boxShadow: {
        card: '0 1px 3px 0 rgba(0,0,0,0.08), 0 1px 2px -1px rgba(0,0,0,0.06)',
        float: '0 10px 25px -5px rgba(0,0,0,0.08), 0 8px 10px -6px rgba(0,0,0,0.05)',
        modal: '0 20px 60px -10px rgba(0,0,0,0.15)',
      },
    },
  },
  plugins: [],
};
